{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "64dfdfbb-9e34-4390-8f80-0e2cf5a63605",
     "showTitle": false,
     "tableResultSettingsMap": {
      "0": {
       "dataGridStateBlob": "{\"version\":1,\"tableState\":{\"columnPinning\":{\"left\":[\"#row_number#\"],\"right\":[]},\"columnSizing\":{},\"columnVisibility\":{}},\"settings\":{\"columns\":{}},\"syncTimestamp\":1774872495203}",
       "filterBlob": null,
       "queryPlanFiltersBlob": null,
       "tableResultIndex": 0
      }
     },
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "\n",
    "-------------------------------------------------------------------------------------------------------------------------------------\n",
    "-- Bright Coffee Shop Analysis - Project\n",
    "-------------------------------------------------------------------------------------------------------------------------------------\n",
    "\n",
    "-- 1.  Data Inspection - Running the entire table\n",
    "select *\n",
    "from `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1`;\n",
    "\n",
    "-- 2. Checking Date range\n",
    "select\n",
    "           min(transaction_date) as min_date,\n",
    "           max(transaction_date) as max_date\n",
    "from `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1`;\n",
    "\n",
    "--3. Checking the different store locations\n",
    "Select distinct store_location\n",
    "from `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1`;\n",
    "-- 3 stores in todal\n",
    "\n",
    "--4. checking the different product categories\n",
    "Select distinct product_category\n",
    "from `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1`;\n",
    "-- 9 product categories\n",
    "\n",
    "--5. Checking the different product types\n",
    "Select distinct product_type\n",
    "from `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1`;\n",
    "-- 29 product types\n",
    "\n",
    "--5. Checking the different product details\n",
    "Select distinct product_detail\n",
    "from `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1`;\n",
    "-- 80 different product categories\n",
    "\n",
    "--6. Checking the nulls\n",
    "select*\n",
    "from `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1`\n",
    "Where unit_price is null\n",
    "or transaction_qty is null \n",
    "or transaction_date is null;\n",
    "-- No nulls found in the data set\n",
    "\n",
    "-- 7. Checking lowest and highest unit price\n",
    "select min(unit_price) as min_price,\n",
    "       max(unit_price) as max_price\n",
    "from `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1`;\n",
    "-- min price is 0.8 and max price is 45.0\n",
    "\n",
    "--8. Extracting  the day and month names\n",
    "select \n",
    "       transaction_date, \n",
    "       dayname(transaction_date) as day_name,\n",
    "       monthname(transaction_date) as month_name\n",
    "from `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1`; \n",
    "\n",
    "--9. Calculating the revenue\n",
    "select unit_price,\n",
    "       transaction_qty,\n",
    "       unit_price*transaction_qty as revenue\n",
    "from `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1`;\n",
    "\n",
    "select *\n",
    "from `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1`;\n",
    "\n",
    "--10. Combing functions to get Clean and enhanced data set. \n",
    "select\n",
    "       transaction_id,\n",
    "       transaction_date,\n",
    "       transaction_time,\n",
    "       transaction_qty,\n",
    "       store_id,\n",
    "       store_location,\n",
    "       product_id,\n",
    "       unit_price,\n",
    "       product_category,\n",
    "       product_type,\n",
    "       product_detail,\n",
    " --- adding columns to combine the table for better insights\n",
    "       dayname(transaction_date) as Day_name,\n",
    "       monthname(transaction_date) as Month_name,\n",
    "       Dayofmonth(transaction_date) as Day_of_month,\n",
    "  Case\n",
    "       when dayname(transaction_date) IN ('Sun','Sat') THEN 'Weekend'\n",
    "       else 'Weekday'\n",
    "  End as day_classification,\n",
    "  -- New column added 5. Time Buckets\n",
    "  Case\n",
    "       when date_format(transaction_time, 'HH:mm:ss') between '05:00:00' and '08:59:00' THEN '01. Rush hour'\n",
    "       When date_format(transaction_time, 'HH:mm:ss') between '09:00:00' and '11:59:00' THEN '02. Mid Morning'\n",
    "       When date_format(transaction_time, 'HH:mm:ss') between '12:00:00' and '15:59:00' THEN '03. Afternoon'\n",
    "       When date_format(transaction_time, 'HH:mm:ss') between '16:00:00' and '18:00:00' THEN '04. Evening'\n",
    "       else '05.Night'\n",
    "  End as Time_classification,\n",
    "  -- New column added 6. Spend Buckets\n",
    "       CASE\n",
    "            when (transaction_qty*unit_price) <=50 THEN '01. Low Spend'\n",
    "            when (transaction_qty*unit_price) Between 51 and 100 THEN '02. Medium Spend'\n",
    "            ELSE '03.High Spend'\n",
    "       END as Spend_bucket,\n",
    "  -- New Column added 7. Revenue\n",
    "       (transaction_qty*unit_price) as Revenue\n",
    "from `workspace`.`default`.`bright_coffee_shop_analysis_case_study_1`;\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "sqlQueryOptions": {
     "applyAutoLimit": true,
     "catalog": "workspace",
     "schema": "default"
    }
   },
   "notebookName": " Project Code: Bright Coffee Shop Data Processing.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
